name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: yarn.lock
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m venv .env && source .env/bin/activate && pip install -r requirements.txt
      - name: Login
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
      - name: Prepare
        run: source .env/bin/activate && yarn && yarn tsc && yarn build
      - name: Build Image
        run: docker build . -t quay.io/apicurio/backstage:latest
      - name: Push To quay.io
        id: push-to-quay
        run: docker push quay.io/apicurio/backstage:latest
